from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Incident(Base):
    __tablename__ = "incidents"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    case_id: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
    )

    narrative: Mapped[str] = mapped_column(Text, nullable=False)

    # Generated by the NLP decoder
    title: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # digital / pdf
    input_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # individual / batch
    processing_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # user / admin / system / batch_upload
    created_by: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    # One incident can have multiple NLP predictions
    predictions: Mapped[list["Prediction"]] = relationship(
        back_populates="incident",
        cascade="all, delete-orphan",
    )


class Prediction(Base):
    __tablename__ = "predictions"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    incident_id: Mapped[int] = mapped_column(
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    energy_source: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    energy_level: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    exposure_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    barrier_status: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    life_saving_rule: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    counterfactual_could_be_fatal_or_permanent: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
    )

    counterfactual_reasoning: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    evidence_phrase: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    recorded_severity: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
    )

    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    evidence_verified: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
    )

    # Raw NLP SPS
    sps: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    # Normalized SPS: 0.0 - 1.0
    normalized_sps: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    sps_breakdown: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
    )

    model_version: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    incident: Mapped["Incident"] = relationship(
        back_populates="predictions",
    )

    feedback: Mapped[list["PredictionFeedback"]] = relationship(
        back_populates="prediction",
        cascade="all, delete-orphan",
    )


class PredictionFeedback(Base):
    __tablename__ = "prediction_feedback"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    prediction_id: Mapped[int] = mapped_column(
        ForeignKey("predictions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    case_id: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )

    # correct / incorrect
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    # Stores corrected fields when the user says prediction is incorrect
    corrected_data: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
    )

    comment: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # user / admin / system / batch_upload
    created_by: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    prediction: Mapped["Prediction"] = relationship(
        back_populates="feedback",
    )


class Cluster(Base):
    __tablename__ = "clusters"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    cluster_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    action: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    incident_clusters: Mapped[list["IncidentCluster"]] = relationship(
        back_populates="cluster",
        cascade="all, delete-orphan",
    )


class IncidentCluster(Base):
    __tablename__ = "incident_clusters"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    incident_id: Mapped[int] = mapped_column(
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    cluster_id: Mapped[int] = mapped_column(
        ForeignKey("clusters.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    cluster: Mapped["Cluster"] = relationship(
        back_populates="incident_clusters",
    )